### ISSUE TITLE
Unavailable page after Login

### ISSUE THREAD

**Issue by GonzaloMolina** [handreassa/prenotami#11]
Sometimes when i can login the page redirects to https://prenotami.esteri.it/Home/Login and the screen is white with a legend "Unavailable"

**Comment by costaguido** [comment]
Hi Gonzalo! Do you find any solution about this issue? I'm getting Unavaible after login.

**Comment by handreassa** [comment]
Guys, how often does it happen to you? If you find this error message, can you please get the html and share it?

**Comment by rghossi** [comment]
After a few minutes running the bot I was logged out by them and got this same message. This is the html:

`<html><head><title>Unavailable</title></head><body>Unavailable</body></html>`

Now every time I run it, it shows the same Unavailable message.

**Comment by johnnywiller** [comment]
Same problem here, "service unavailable" after login page on selenium and fine when running manually

**Comment by johnnywiller** [comment]
Hey, to fix "service unavailable" just add
`chrome_options.add_argument('--disable-gpu')` makes it work!

**Comment by handreassa** [comment]
@johnnywiller thanks for that! I am pushing some changes today, even not using this anymore it's a good way to keep this repo updated. Any other ideas feel free to reach out!
