### ISSUE TITLE
Element not found when scheduler not available

### ISSUE THREAD

**Issue by bernardokowacic** [handreassa/prenotami#3]
Hello!

I'm trying to schedule my citizenship through the Curitiba consulate, but when the scheduler isn't available, the system throws the exception `NoSuchElementException` and asks to fill in the values manually, but the site is on a screen written 'unavailable', as you can see in the prints below

![image](https://user-images.githubusercontent.com/11669811/223127331-5c8ce57c-f5e2-4b2e-a5a1-e393aad02f25.png)
![image](https://user-images.githubusercontent.com/11669811/223127400-381d9a1b-542b-4b82-8f26-5f78373f2b29.png)

**Comment by handreassa** [comment]
Hey there, already have had the same issue here, it's an unexpected situation where the main loop breaks. It needs some additional development. Marked as a bug to keep track inside this repo.

**Comment by bernardokowacic** [comment]
I noticed that this happens when the login button is clicked. Maybe something related to Google Captcha?

I'm using WSL2 with Ubuntu 22 and Chrome 110

**Comment by giovanit** [comment]
I have the same error after login "unavailable". Maybe my logs can help you.

INFO:Timestamp: 2023-03-29 09:03:30.457925 - Successfuly logged in.
INFO:Timestamp: 2023-03-29 09:03:33.157031 - Element WlNotAvailable not found. Start filling the forms.
INFO:Exception 'WebDriver' object has no attribute 'find_element_by_id'

**Comment by bernardokowacic** [comment]
Maybe it is some captcha related issue? I saw a class element related to invisible gcaptcha in the submit button

**Comment by alantody** [comment]
Anynone help with this 

![Screenshot_3](https://github.com/handreassa/prenotami/assets/35308562/ed460fd8-eb8b-4d3c-b637-b7a46a15654c)

**Comment by handreassa** [comment]
Just tried to run here and it seems that the exception is not happening anymore. Can you try as well? @giovanit @bernardokowacic

**Comment by handreassa** [comment]
> Anynone help with this
> 
> ![Screenshot_3](https://user-images.githubusercontent.com/35308562/244490679-ed460fd8-eb8b-4d3c-b637-b7a46a15654c.jpg)

Are you using any additional chrome options? Is the code exactly the same than in this repo? If it's different could you please provide some snippet from the webdriver class initialization?

**Comment by handreassa** [comment]
@alantody try to delete the cached binary and run it again.

Just for reference, this is the init on web driver class. If deleting the binary doesn't do the job, maybe try commenting the chrome options (detach and start maximized).

```python 
def __init__(self, executable_path="chromedriver", port=0,
             options=None, service_args=None,
             desired_capabilities=None, service_log_path=None,
             chrome_options=None):
    """
    Creates a new instance of the chrome driver.

    Starts the service and then creates new instance of chrome driver.

    :Args:
     - executable_path - path to the executable. If the default is used it assumes the executable is in the $PATH
    ```

**Comment by bernardokowacic** [comment]
Hello guys, I've tried here and looks like that it works with chromedriver 114. In the previous versions it doesn't work for some reason. We can close this issue now.

**Comment by alantody** [comment]
My issue is solved now, something wrong with my permissions

Im run this commands to solve:

sudo chown -R myuser:myuser /home/myuser/.config
sudo chown -R myuser:myuser /home/myuser
Reboot

and Working Great!, Thanks for the nice code!
