### ISSUE TITLE
residencia.pdf

### ISSUE THREAD

**Issue by peyafaguerre** [handreassa/prenotami#4]
It may help to clarify what information should be included in the pdf.

**Comment by handreassa** [comment]
It has to demonstrate that you live in the address that is covered by that consulate. For example it can be utility bills (phone, electricity, etc). For example, Curitiba consulate states this in their requirements (https://conscuritiba.esteri.it/pt/news/dal_consolato/2021/07/nova-modalidade-prenot-mi-cidadania/):

 

> D) comprovante de residência nominal de cada interessado maior de idade. È imprescindível comprovar residência no Paraná ou Santa Catarina nos 12 meses anteriores à data do agendamento. Podem ser apresentados, por exemplo, contas de luz, água, telefonia, internet onde conste o consumo nos últimos 12 meses, folha de rosto das últimas duas declarações de imposto de renda, certidão de quitação eleitoral com a data de inscrição na zona eleitoral, declaração de matrícula/frequência em instituição de ensino, comprovante de pagamento de aposentadoria, entre outros. Em caso de dúvidas este Consulado Geral se reserva no direito de solicitar mais comprovantes.

**Comment by handreassa** [comment]
Just added that info to the readme file.
